# Generated by Django 5.0 on 2025-02-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralInfor',
            new_name='GeneralInfo',
        ),
    ]
