# Generated by Django 5.0 on 2025-02-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='Facenook_url',
            new_name='Facebook_url',
        ),
    ]
