# Generated by Django 5.0 on 2025-02-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='catagory',
            new_name='category',
        ),
    ]
