# Generated by Django 5.0 on 2025-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_first_name_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
