# Generated by Django 5.0 on 2025-02-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
