# Generated by Django 5.0 on 2025-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='Japen', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Japen', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
