# Generated by Django 5.0 on 2025-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_first_name_author_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herocontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_line', models.CharField(max_length=255)),
                ('hero_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('video_ur', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Content',
                'verbose_name_plural': 'Hero Contents',
                'ordering': ['display_order'],
            },
        ),
    ]
