# Generated by Django 5.0 on 2025-02-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_herocontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herocontent',
            old_name='video_ur',
            new_name='video_url',
        ),
    ]
