# Generated by Django 5.0 on 2025-02-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_video_ur_herocontent_video_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Herocontent',
            new_name='HeroSection',
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['display_order'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='tag_line',
            new_name='tag_lines',
        ),
    ]
