# Generated by Django 5.0 on 2025-02-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_herocontent_herosection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='user_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
