# Generated by Django 5.0 on 2025-03-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_testimonial_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='company_name',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='company_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
