# Generated by Django 5.0 on 2025-03-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_generalinfo_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='Linkedin_url',
            new_name='Telegram_url',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='Twitter_url',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='instagram_url',
        ),
    ]
