# Generated by Django 5.0 on 2025-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_linkedin_url_generalinfo_telegram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=255),
        ),
    ]
