# Generated by Django 5.0 on 2025-05-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_generalinfo_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
