# Generated by Django 5.0 on 2025-05-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_author_country_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='Customer phone number', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('machine_size', models.CharField(choices=[('35kVA', '35kVA'), ('50kVA', '50kVA'), ('100kVA', '100kVA')], max_length=10)),
                ('duration', models.CharField(help_text='E.g., 6 months, 1 year', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Total rental cost in USD', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(help_text='Type of machine (e.g., Generator, UPS)', max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('issue_description', models.TextField()),
                ('preferred_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_issues/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
            ],
        ),
    ]
