# Generated by Django 5.0 on 2025-06-01 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rentalbooking_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalbooking',
            name='duration',
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='rental_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Start date of the rental'),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='return_date',
            field=models.DateField(blank=True, help_text='End date of the rental', null=True),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='machine_size',
            field=models.CharField(choices=[('35kVA', '45kVA'), ('50kVA', '60kVA'), ('100kVA', '150kVA')], max_length=10),
        ),
    ]
