# Generated by Django 5.0 on 2025-06-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
