# Generated by Django 5.0 on 2025-06-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_product_author_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='products/additional/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/additional/'),
        ),
    ]
