# Generated by Django 5.0 on 2025-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_product_additional_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ats_panel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol')], default='diesel', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='installation_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='maintenance_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='noise_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='onsite_technician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power_backup_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='power_output',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='replacement_guarantee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='runtime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tank_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
