# Generated by Django 5.0 on 2025-06-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_product_ats_panel_product_free_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('for_rent', 'For Rent'), ('out_of_stock', 'Out of Stock')], default='available', max_length=20),
        ),
    ]
