# Generated by Django 5.0 on 2025-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total rental cost in USD', max_digits=10, null=True),
        ),
    ]
