# Generated by Django 5.0 on 2025-06-09 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_rentalbooking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbooking',
            name='ats_panel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='onsite_technician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='power_backup_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_bookings', to='app.product'),
        ),
    ]
