# Generated by Django 5.0 on 2025-06-10 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_rentalbooking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalbooking',
            name='machine_size',
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_images/'),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='order_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deposit_paid', 'Deposit Paid'), ('fully_paid', 'Fully Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_bookings', to='app.product'),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
