# Generated by Django 5.0 on 2025-06-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_contactmessage_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='user_image',
            field=models.ImageField(blank=True, default='assets/img/logo.png', max_length=255, null=True, upload_to=''),
        ),
    ]
